### ISSUE TITLE
oracle 12.2 compiling issue for json_value

### ISSUE THREAD

**Issue by WUJINGGITHUB** [pljson/pljson#101]
We encounter compiling err as:
Compilation errors for TYPE BODY XLS_ADMIN.JSON_VALUE
Error: PLS-00103: Encountered the symbol ";" when expecting one of the following:    (
Line: 64  Text: return json_value;

62 static function makenull return json_value as
63   begin
64    return json_value;
65  end makenull;

we are using oracle 12.2 .  the string JSON_VALUE has become reserved keyword in Oracle  Release 12 due to their expanding JSON support. And this only happens when the Oracle Db parameter named 'compatible' is set to 12.2. It works fine with oracle 12.1.

**Comment by dsnz** [comment]
Thank you for notifying.
We had received a Pull Request recently that specifically fixed 12.2 installation and I am surprised.
Please allow 24 hours to install a new 12.2 installation and see and fix every such 12.2 related naming issue.

**Comment by dsnz** [comment]
Hello,

Please use the develop branch and type pljson_value in your code. We have renamed all types and packages to start with 'pljson_' to avoid such conflicts.

**Comment by jsumners** [comment]
Duplicate #83

**Comment by WUJINGGITHUB** [comment]
Thanks

在 2017年8月2日，下午8:14，James Sumners <notifications@github.com<mailto:notifications@github.com>> 写道：


Duplicate #83<https://github.com/pljson/pljson/issues/83>
